### ISSUE TITLE
Hi How to translate Alert Messages in Multilangual application?

### ISSUE THREAD

**Issue by pieinn** [ferdinandfrank/vue-forms#3]
Thank you for useful repository.

Please advice how to translate  Alert Messages, because my project is multilingual.

And how to show validation with SweetAlert or Tooltip?

This rules: 
'name' => 'required|min:3|max:255',
            'mobile_no' => 'phone:KZ,RU',
            'message' => 'required|max:65535',
            'email' => 'required|email',

<img width="1440" alt="2017-11-21 16 48 48" src="https://user-images.githubusercontent.com/29000827/33068579-f704cd16-cedb-11e7-9cbd-baa6c92bbbf5.png">

**Comment by ferdinandfrank** [comment]
You can show the validation errors before the form gets submitted by setting the `rules` property on your input components ([see the Validation section for details](https://github.com/ferdinandfrank/vue-forms#validation)). On these rules you can also specify a translated error message for each particular rule with the help of Laravel's translations. In the case of your `name` input field the component instance should be defined as followed:

```xhtml
<form-input name="name" label="name" :rules=[{required: true, message: '{{ trans('validation.required') }}'}, {min: 3, message: "{{ trans('validation.min', ['min' => 3]) }}"}, {max: 255, message: "{{ trans('validation.min', ['min' => 255]) }}"}]> </form-input>
```
By default these error messaged should be shown below the input automatically with the help of Bootstrap, but feel free to adapt all of the components to your needs and your design. The error message that is currently shown on the input is saved in a data attribute called `errorMessage`. So, you can adapt your input component's by watching this attribute and show an alert message (or tooltip) whenever this value changes.

For the alert messages based on validation errors from the server I was still using Laravel's old error format (That's why only the message in your image will be shown to the user). I will fix this issue within the next minutes. Sorry about that and thanks for the hint.

**Comment by pieinn** [comment]
Thank you! Just Works! Please advice how to clear inputs after submission?

My Controller: return redirect()->back()->withInput();

**Comment by ferdinandfrank** [comment]
You can simply add the prop `clear` with the value `true` to your `AjaxFormComponent`:

```html
<ajax-form method="post" action="path/to/server" :clear=true>
...
</ajax-form>
```

When you submit an ajax request to the server via an `AjaxFormComponent`, the server should return a json response in order to control the further handling of the `AjaxFormComponent`. 
Example for showing a success alert message and redirect the user after the alert message was shown:

```php
return response()->json([
    'redirect'  => route('home'),
    'alert' => [
        'title'   => 'Success',
        'message' => 'The request was successful!'
    ]
]);
```
You can view the full list of json params for the response [here](https://github.com/ferdinandfrank/vue-forms#parsing-responses-from-the-server).
I will make a better documentation within the next days!
