### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by pieinn** [ferdinandfrank/vue-forms#5]
In my controller i have function redirect to . ... but when i use <ajax-form> not redirect?
Please advice how to resolve this issue.
Thanks!

**Comment by ferdinandfrank** [comment]
That's because the form components expect the response to be in a JSON format. As stated [here](https://ferdinandfrank.github.io/vue-forms/#server-response-handling), you can control the handling after the form was processed by the server by specifying specific keys in the JSON response. If you want to redirect the user after the form was processed you need to return the following JSON data with the key `redirect` and your redirect url as the value in your controller method:

```php
return response()->json([
    'redirect' => route('home') 
]);
```

**Comment by pieinn** [comment]
Thank you, I understood how it works!

But redirect to back, not to my home page:

```
`return response()->json([
    'redirect' => route('home') 
]);`
```


Sorry, I'm newbie...

**Comment by pieinn** [comment]
All works thank you!
